apiVersion: v1
kind: Service
metadata:
  name: nextjsmongoose-service
spec:
  selector:
    app: nextjsmongoose
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
